version: '3'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: api
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
    #volumes:
      #- rimal_db:/var/lib/mysql
  backend:
    #image: jbalceda/rimal-sb
    build: .
    ports:
      - 8082:8082
    depends_on:
      - db
    restart: unless-stopped
    #volumes:
    #  - rimal_backend:/opt/rimal/storage
  
