server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  profiles: default

  dataSource:
    url: jdbc:mysql://localhost:3306/api?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    initialization-mode: always

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


